### ISSUE TITLE
Missing Hexagon: Is this data being resold?

### ISSUE THREAD

**Issue by sevaan** [sidewalklabs/dtpr#11]
If the purpose of these symbols is to provide transparency into how data is being collected and used, then users should be informed if the data being collected is for resale or not.

**Comment by patrickkeenan** [comment]
Yup, resale is one of the data processing icons in the taxonomy.

**Comment by jackielu** [comment]
Specifically, row 5 in the [Access table in the taxonomy](https://airtable.com/shrsW7o7ji3VjsZSz/tblJ7hGDeOXhWJbjT/viwW4Eg0Zovwd1KfC?blocks=hide) 

![image](https://user-images.githubusercontent.com/7483079/58263616-58a87e00-7d4a-11e9-8ce9-463997abfae0.png)
